import 'package:flutter/foundation.dart';

/// How the student signs in.
enum AuthMode {
  /// Sends `dev:<email>` as the token. Only accepted by a backend running with
  /// `AUTH_PROVIDER=dev`, so it never works against production.
  dev,

  /// Firebase Authentication with email and password. Needs the Firebase
  /// project files generated by `flutterfire configure`.
  firebase,
}

/// Build-time settings, passed with `--dart-define`:
///
/// ```sh
/// flutter run --dart-define=API_BASE_URL=http://192.168.0.10:8000/api/v1
/// flutter run --dart-define=AUTH_MODE=firebase
/// ```
abstract final class AppConfig {
  static const _apiBaseUrl = String.fromEnvironment('API_BASE_URL');
  static const _authMode = String.fromEnvironment(
    'AUTH_MODE',
    defaultValue: 'dev',
  );

  /// Where the SENECApp backend lives, up to and including `/api/v1`.
  ///
  /// Without an override, the Android emulator reaches the laptop through its
  /// `10.0.2.2` alias and everything else (Chrome, iOS simulator) through
  /// `localhost`. A physical phone always needs the override.
  static String get apiBaseUrl {
    if (_apiBaseUrl.isNotEmpty) return _apiBaseUrl;
    final emulatorHost =
        !kIsWeb && defaultTargetPlatform == TargetPlatform.android;
    return emulatorHost
        ? 'http://10.0.2.2:8000/api/v1'
        : 'http://localhost:8000/api/v1';
  }

  static AuthMode get authMode =>
      _authMode == 'firebase' ? AuthMode.firebase : AuthMode.dev;

  /// Firebase (sign-in and push notifications) only runs once the project is
  /// configured, which `AUTH_MODE=firebase` stands for.
  static bool get firebaseEnabled => authMode == AuthMode.firebase;

  static const microsoftTenant = String.fromEnvironment(
    'MICROSOFT_TENANT',
    defaultValue: 'uniandes.edu.co',
  );

  /// The backend only accepts university accounts. Checked here too so a typo
  /// is caught before a round trip.
  static const allowedEmailDomain = 'uniandes.edu.co';
}
